### ISSUE TITLE
BxDecay0 1.1.1 and MT mode

### ISSUE THREAD

**Issue by gipert** [legend-exp/remage#50]
BxDecay0 might be thread-safe now: https://github.com/BxCppDev/bxdecay0/pull/29. Needs testing.

**Comment by ManuelHu** [comment]
* verified that this is fixed with latest bxdecay0 and our tests. The newly added MT-enabled extra test runs without crashes even after a lot of (>200) of repetitions
* I added a cmake version check, to disable the warning, in ee79869ee77808833ccab385a6175f98e72af959
* Unfortunately, we still have to wait for https://github.com/BxCppDev/bxdecay0/issues/31 to use it in our containers (or patch it manually)
